// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Solar_UI

#ifndef _SOLAR_UI_UI_H
#define _SOLAR_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_home
void ui_home_screen_init(void);
extern lv_obj_t * ui_home;
extern lv_obj_t * ui_pvIcon;
extern lv_obj_t * ui_pvLine;
extern lv_obj_t * ui_pvWatts;
extern lv_obj_t * ui_pvTotal;
extern lv_obj_t * ui_pvTotalUnits;
extern lv_obj_t * ui_loadWatts;
extern lv_obj_t * ui_battIcon;
extern lv_obj_t * ui_battLine;
extern lv_obj_t * ui_battSoc;
extern lv_obj_t * ui_battWatts;
extern lv_obj_t * ui_battDailyCharge;
extern lv_obj_t * ui_battDailyDischargeUnit;
extern lv_obj_t * ui_battDailyDischarge;
extern lv_obj_t * ui_battDailyChargeUnit;
extern lv_obj_t * ui_battDischargeIcon;
extern lv_obj_t * ui_battChargeIcon;
extern lv_obj_t * ui_gridIcon;
extern lv_obj_t * ui_gridLine;
extern lv_obj_t * ui_gridWatts;
extern lv_obj_t * ui_gridDailyExport;
extern lv_obj_t * ui_gridDailyExportUnit;
extern lv_obj_t * ui_gridDailyImport;
extern lv_obj_t * ui_gridDailyImportUnit;
extern lv_obj_t * ui_gridExportArrow;
extern lv_obj_t * ui_gridImportArrow;
extern lv_obj_t * ui_loadIcon;
extern lv_obj_t * ui_loadLine;
extern lv_obj_t * ui_loadTotal;
extern lv_obj_t * ui_loadTotalUnits;
extern lv_obj_t * ui_inverterIcon;
extern lv_obj_t * ui_Inverter;
extern lv_obj_t * ui_SunsynkLogo;
void ui_event_Image10(lv_event_t * e);
extern lv_obj_t * ui_Image10;
// SCREEN: ui_config
void ui_config_screen_init(void);
extern lv_obj_t * ui_config;
extern lv_obj_t * ui_settingsTabs;
extern lv_obj_t * ui_WiFi;
extern lv_obj_t * ui_ssidLabel;
extern lv_obj_t * ui_networkSSID;
extern lv_obj_t * ui_networkPasswordLabel;
extern lv_obj_t * ui_networkPassword;
extern lv_obj_t * ui_Sunsynk;
extern lv_obj_t * ui_usernameLabel;
extern lv_obj_t * ui_username;
extern lv_obj_t * ui_apiPasswordLabel;
extern lv_obj_t * ui_apiPassword;
extern lv_obj_t * ui_inverterId;
extern lv_obj_t * ui_inverterIdLabel;
extern lv_obj_t * ui_btnSaveSettings;
extern lv_obj_t * ui_btnSaveSettingsLabel;
void ui_event_btnCancelSettings(lv_event_t * e);
extern lv_obj_t * ui_btnCancelSettings;
extern lv_obj_t * ui_btnCancelSettingsLabel;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_1549501229);    // assets\icons8-solar-panel-100.png
LV_IMG_DECLARE(ui_img_1933564998);    // assets\line-75-4.png
LV_IMG_DECLARE(ui_img_670870020);    // assets\icons8-charging-battery-90.png
LV_IMG_DECLARE(ui_img_1261930360);    // assets\line-75-4-inv.png
LV_IMG_DECLARE(ui_img_705529016);    // assets\icons8-arrow-30.png
LV_IMG_DECLARE(ui_img_264836261);    // assets\icons8-transmission-tower-100.png
LV_IMG_DECLARE(ui_img_1076282785);    // assets\icons8-house-100.png
LV_IMG_DECLARE(ui_img_1551709364);    // assets\sunsynk-logo-40px.png
LV_IMG_DECLARE(ui_img_540100334);    // assets\icons8-settings-50.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
