// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Solar_UI

#include "ui.h"

void ui_config_screen_init(void)
{
    ui_config = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_config, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settingsTabs = lv_tabview_create(ui_config, LV_DIR_TOP, 35);
    lv_obj_set_width(ui_settingsTabs, 480);
    lv_obj_set_height(ui_settingsTabs, 245);
    lv_obj_set_x(ui_settingsTabs, 0);
    lv_obj_set_y(ui_settingsTabs, -35);
    lv_obj_set_align(ui_settingsTabs, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_settingsTabs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WiFi = lv_tabview_add_tab(ui_settingsTabs, "WiFi Network");
    lv_obj_set_style_bg_color(ui_WiFi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ssidLabel = lv_label_create(ui_WiFi);
    lv_obj_set_width(ui_ssidLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ssidLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ssidLabel, -310);
    lv_obj_set_y(ui_ssidLabel, -50);
    lv_obj_set_align(ui_ssidLabel, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_ssidLabel, "Network Name:");
    lv_obj_set_style_text_font(ui_ssidLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_networkSSID = lv_textarea_create(ui_WiFi);
    lv_obj_set_width(ui_networkSSID, 250);
    lv_obj_set_height(ui_networkSSID, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_networkSSID, 47);
    lv_obj_set_y(ui_networkSSID, -50);
    lv_obj_set_align(ui_networkSSID, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_networkSSID, 128);
    lv_textarea_set_placeholder_text(ui_networkSSID, "SSID");
    lv_textarea_set_one_line(ui_networkSSID, true);
    lv_obj_clear_flag(ui_networkSSID, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_networkPasswordLabel = lv_label_create(ui_WiFi);
    lv_obj_set_width(ui_networkPasswordLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_networkPasswordLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_networkPasswordLabel, -310);
    lv_obj_set_y(ui_networkPasswordLabel, -5);
    lv_obj_set_align(ui_networkPasswordLabel, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_networkPasswordLabel, "Password:");
    lv_obj_set_style_text_font(ui_networkPasswordLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_networkPassword = lv_textarea_create(ui_WiFi);
    lv_obj_set_width(ui_networkPassword, 250);
    lv_obj_set_height(ui_networkPassword, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_networkPassword, 47);
    lv_obj_set_y(ui_networkPassword, -5);
    lv_obj_set_align(ui_networkPassword, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_networkPassword, 128);
    lv_textarea_set_placeholder_text(ui_networkPassword, "Password");
    lv_textarea_set_one_line(ui_networkPassword, true);
    lv_textarea_set_password_mode(ui_networkPassword, true);
    lv_obj_clear_flag(ui_networkPassword, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Sunsynk = lv_tabview_add_tab(ui_settingsTabs, "Sunsynk API");

    ui_usernameLabel = lv_label_create(ui_Sunsynk);
    lv_obj_set_width(ui_usernameLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_usernameLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_usernameLabel, -300);
    lv_obj_set_y(ui_usernameLabel, -61);
    lv_obj_set_align(ui_usernameLabel, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_usernameLabel, "Username:");
    lv_obj_set_style_text_font(ui_usernameLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_username = lv_textarea_create(ui_Sunsynk);
    lv_obj_set_width(ui_username, 235);
    lv_obj_set_height(ui_username, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_username, 47);
    lv_obj_set_y(ui_username, -60);
    lv_obj_set_align(ui_username, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_username, 64);
    lv_textarea_set_placeholder_text(ui_username, "name@example.com");
    lv_textarea_set_one_line(ui_username, true);

    ui_apiPasswordLabel = lv_label_create(ui_Sunsynk);
    lv_obj_set_width(ui_apiPasswordLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_apiPasswordLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_apiPasswordLabel, -300);
    lv_obj_set_y(ui_apiPasswordLabel, -15);
    lv_obj_set_align(ui_apiPasswordLabel, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_apiPasswordLabel, "Password:");
    lv_obj_set_style_text_font(ui_apiPasswordLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_apiPassword = lv_textarea_create(ui_Sunsynk);
    lv_obj_set_width(ui_apiPassword, 235);
    lv_obj_set_height(ui_apiPassword, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_apiPassword, 47);
    lv_obj_set_y(ui_apiPassword, -15);
    lv_obj_set_align(ui_apiPassword, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_apiPassword, 64);
    lv_textarea_set_placeholder_text(ui_apiPassword, "Password");
    lv_textarea_set_one_line(ui_apiPassword, true);
    lv_textarea_set_password_mode(ui_apiPassword, true);

    ui_inverterId = lv_textarea_create(ui_Sunsynk);
    lv_obj_set_width(ui_inverterId, 235);
    lv_obj_set_height(ui_inverterId, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_inverterId, 47);
    lv_obj_set_y(ui_inverterId, 30);
    lv_obj_set_align(ui_inverterId, LV_ALIGN_CENTER);
    if("0-9" == "") lv_textarea_set_accepted_chars(ui_inverterId, NULL);
    else lv_textarea_set_accepted_chars(ui_inverterId, "0-9");
    lv_textarea_set_max_length(ui_inverterId, 64);
    lv_textarea_set_placeholder_text(ui_inverterId, "12345678");
    lv_textarea_set_one_line(ui_inverterId, true);

    ui_inverterIdLabel = lv_label_create(ui_Sunsynk);
    lv_obj_set_width(ui_inverterIdLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_inverterIdLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_inverterIdLabel, -300);
    lv_obj_set_y(ui_inverterIdLabel, 30);
    lv_obj_set_align(ui_inverterIdLabel, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_inverterIdLabel, "Inverter ID:");
    lv_obj_set_style_text_font(ui_inverterIdLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSaveSettings = lv_btn_create(ui_config);
    lv_obj_set_width(ui_btnSaveSettings, 160);
    lv_obj_set_height(ui_btnSaveSettings, 50);
    lv_obj_set_x(ui_btnSaveSettings, -100);
    lv_obj_set_y(ui_btnSaveSettings, 125);
    lv_obj_set_align(ui_btnSaveSettings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSaveSettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnSaveSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnSaveSettingsLabel = lv_label_create(ui_btnSaveSettings);
    lv_obj_set_width(ui_btnSaveSettingsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_btnSaveSettingsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_btnSaveSettingsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_btnSaveSettingsLabel, "Save");

    ui_btnCancelSettings = lv_btn_create(ui_config);
    lv_obj_set_width(ui_btnCancelSettings, 160);
    lv_obj_set_height(ui_btnCancelSettings, 50);
    lv_obj_set_x(ui_btnCancelSettings, 100);
    lv_obj_set_y(ui_btnCancelSettings, 125);
    lv_obj_set_align(ui_btnCancelSettings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnCancelSettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnCancelSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnCancelSettings, lv_color_hex(0xC6C5C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnCancelSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnCancelSettingsLabel = lv_label_create(ui_btnCancelSettings);
    lv_obj_set_width(ui_btnCancelSettingsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_btnCancelSettingsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_btnCancelSettingsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_btnCancelSettingsLabel, "Cancel");

    lv_obj_add_event_cb(ui_btnCancelSettings, ui_event_btnCancelSettings, LV_EVENT_ALL, NULL);

}
