// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Solar_UI_480x320

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_homeScreen
void ui_homeScreen_screen_init(void);
lv_obj_t * ui_homeScreen;
lv_obj_t * ui_pvIcon;
lv_obj_t * ui_pvLine;
lv_obj_t * ui_pvWatts;
lv_obj_t * ui_pvWattsUnit;
lv_obj_t * ui_pvTotal;
lv_obj_t * ui_pvTotalUnits;
lv_obj_t * ui_loadWatts;
lv_obj_t * ui_loadWattsUnit;
lv_obj_t * ui_battIcon;
lv_obj_t * ui_battLine;
lv_obj_t * ui_battSoc;
lv_obj_t * ui_battSocRate;
lv_obj_t * ui_battWatts;
lv_obj_t * ui_battWattsUnit;
lv_obj_t * ui_battDailyCharge;
lv_obj_t * ui_battDailyDischargeUnit;
lv_obj_t * ui_battDailyDischarge;
lv_obj_t * ui_battDailyChargeUnit;
lv_obj_t * ui_battDischargeIcon;
lv_obj_t * ui_battChargeIcon;
lv_obj_t * ui_gridIcon;
lv_obj_t * ui_gridLine;
lv_obj_t * ui_gridWatts;
lv_obj_t * ui_pvWattsUnit1;
lv_obj_t * ui_gridDailyExport;
lv_obj_t * ui_gridDailyExportUnit;
lv_obj_t * ui_gridDailyImport;
lv_obj_t * ui_gridDailyImportUnit;
lv_obj_t * ui_gridExportArrow;
lv_obj_t * ui_gridImportArrow;
lv_obj_t * ui_loadIcon;
lv_obj_t * ui_loadLine;
lv_obj_t * ui_loadTotal;
lv_obj_t * ui_loadTotalUnits;
lv_obj_t * ui_Inverter;
lv_obj_t * ui_time;
lv_obj_t * ui_syncing;
lv_obj_t * ui_wifiHigh;
lv_obj_t * ui_wifiMed;
lv_obj_t * ui_wifiLow;
lv_obj_t * ui_infoPanel;
lv_obj_t * ui_infoBox;
lv_obj_t * ui_infoText;
lv_obj_t * ui_settingsIcon;
void ui_event_inverterTouch(lv_event_t * e);
lv_obj_t * ui_inverterTouch;
void ui_event_pvTouch(lv_event_t * e);
lv_obj_t * ui_pvTouch;
void ui_event_gridTouch(lv_event_t * e);
lv_obj_t * ui_gridTouch;
void ui_event_battTouch(lv_event_t * e);
lv_obj_t * ui_battTouch;
void ui_event_loadTouch(lv_event_t * e);
lv_obj_t * ui_loadTouch;


// SCREEN: ui_inverterScreen
void ui_inverterScreen_screen_init(void);
void ui_event_inverterScreen(lv_event_t * e);
lv_obj_t * ui_inverterScreen;
lv_obj_t * ui_invScreenHeading;


// SCREEN: ui_pvScreen
void ui_pvScreen_screen_init(void);
void ui_event_pvScreen(lv_event_t * e);
lv_obj_t * ui_pvScreen;
lv_obj_t * ui_pvScreenHeading;


// SCREEN: ui_gridScreen
void ui_gridScreen_screen_init(void);
void ui_event_gridScreen(lv_event_t * e);
lv_obj_t * ui_gridScreen;
lv_obj_t * ui_gridScreenHeading;


// SCREEN: ui_battScreen
void ui_battScreen_screen_init(void);
void ui_event_battScreen(lv_event_t * e);
lv_obj_t * ui_battScreen;
lv_obj_t * ui_battScreenHeading;
lv_obj_t * ui_battIcon2;
lv_obj_t * ui_battCapLabel;
lv_obj_t * ui_battCapValue;
lv_obj_t * ui_battSocLabel;
lv_obj_t * ui_battSocValue;
lv_obj_t * ui_battPwrLabel;
lv_obj_t * ui_battPwrValue;
lv_obj_t * ui_battCurrLabel;
lv_obj_t * ui_battCurrValue;
lv_obj_t * ui_voltLabel;
lv_obj_t * ui_battVoltValue;
lv_obj_t * ui_tempLabel;
lv_obj_t * ui_battTempValue;


// SCREEN: ui_loadScreen
void ui_loadScreen_screen_init(void);
void ui_event_loadScreen(lv_event_t * e);
lv_obj_t * ui_loadScreen;
lv_obj_t * ui_loadScreenHeading;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_867608463[1] = {&ui_img_705529016};
const lv_img_dsc_t * ui_imgset_1070557679[1] = {&ui_img_670870020};
const lv_img_dsc_t * ui_imgset_1885365100[1] = {&ui_img_1076282785};
const lv_img_dsc_t * ui_imgset_59742990[1] = {&ui_img_226794803};
const lv_img_dsc_t * ui_imgset_1375169470[1] = {&ui_img_1549501229};
const lv_img_dsc_t * ui_imgset_1399112042[1] = {&ui_img_264836261};
const lv_img_dsc_t * ui_imgset_535857063[1] = {&ui_img_1683162281};
const lv_img_dsc_t * ui_imgset_1178831554[1] = {&ui_img_1933564998};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_inverterTouch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_inverterScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_inverterScreen_screen_init);
    }
}
void ui_event_pvTouch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_pvScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_pvScreen_screen_init);
    }
}
void ui_event_gridTouch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_gridScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_gridScreen_screen_init);
    }
}
void ui_event_battTouch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_battScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_battScreen_screen_init);
    }
}
void ui_event_loadTouch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_loadScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_loadScreen_screen_init);
    }
}
void ui_event_inverterScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_homeScreen_screen_init);
    }
}
void ui_event_pvScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_homeScreen_screen_init);
    }
}
void ui_event_gridScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_homeScreen_screen_init);
    }
}
void ui_event_battScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_homeScreen_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        detailScreenOnLoad(e);
    }
}
void ui_event_loadScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_homeScreen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_homeScreen_screen_init();
    ui_inverterScreen_screen_init();
    ui_pvScreen_screen_init();
    ui_gridScreen_screen_init();
    ui_battScreen_screen_init();
    ui_loadScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_homeScreen);
}
