// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Solar_UI_480x320

#ifndef _SOLAR_UI_480X320_UI_H
#define _SOLAR_UI_480X320_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_homeScreen
void ui_homeScreen_screen_init(void);
extern lv_obj_t * ui_homeScreen;
extern lv_obj_t * ui_pvIcon;
extern lv_obj_t * ui_pvLine;
extern lv_obj_t * ui_pvWatts;
extern lv_obj_t * ui_pvWattsUnit;
extern lv_obj_t * ui_pvTotal;
extern lv_obj_t * ui_pvTotalUnits;
extern lv_obj_t * ui_loadWatts;
extern lv_obj_t * ui_loadWattsUnit;
extern lv_obj_t * ui_battIcon;
extern lv_obj_t * ui_battLine;
extern lv_obj_t * ui_battSoc;
extern lv_obj_t * ui_battSocRate;
extern lv_obj_t * ui_battWatts;
extern lv_obj_t * ui_battWattsUnit;
extern lv_obj_t * ui_battDailyCharge;
extern lv_obj_t * ui_battDailyDischargeUnit;
extern lv_obj_t * ui_battDailyDischarge;
extern lv_obj_t * ui_battDailyChargeUnit;
extern lv_obj_t * ui_battDischargeIcon;
extern lv_obj_t * ui_battChargeIcon;
extern lv_obj_t * ui_gridIcon;
extern lv_obj_t * ui_gridLine;
extern lv_obj_t * ui_gridWatts;
extern lv_obj_t * ui_pvWattsUnit1;
extern lv_obj_t * ui_gridDailyExport;
extern lv_obj_t * ui_gridDailyExportUnit;
extern lv_obj_t * ui_gridDailyImport;
extern lv_obj_t * ui_gridDailyImportUnit;
extern lv_obj_t * ui_gridExportArrow;
extern lv_obj_t * ui_gridImportArrow;
extern lv_obj_t * ui_loadIcon;
extern lv_obj_t * ui_loadLine;
extern lv_obj_t * ui_loadTotal;
extern lv_obj_t * ui_loadTotalUnits;
extern lv_obj_t * ui_Inverter;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_syncing;
extern lv_obj_t * ui_wifiHigh;
extern lv_obj_t * ui_wifiMed;
extern lv_obj_t * ui_wifiLow;
extern lv_obj_t * ui_infoPanel;
extern lv_obj_t * ui_infoBox;
extern lv_obj_t * ui_infoText;
extern lv_obj_t * ui_settingsIcon;
void ui_event_inverterTouch(lv_event_t * e);
extern lv_obj_t * ui_inverterTouch;
void ui_event_pvTouch(lv_event_t * e);
extern lv_obj_t * ui_pvTouch;
void ui_event_gridTouch(lv_event_t * e);
extern lv_obj_t * ui_gridTouch;
void ui_event_battTouch(lv_event_t * e);
extern lv_obj_t * ui_battTouch;
void ui_event_loadTouch(lv_event_t * e);
extern lv_obj_t * ui_loadTouch;
// SCREEN: ui_inverterScreen
void ui_inverterScreen_screen_init(void);
void ui_event_inverterScreen(lv_event_t * e);
extern lv_obj_t * ui_inverterScreen;
extern lv_obj_t * ui_invScreenHeading;
// SCREEN: ui_pvScreen
void ui_pvScreen_screen_init(void);
void ui_event_pvScreen(lv_event_t * e);
extern lv_obj_t * ui_pvScreen;
extern lv_obj_t * ui_pvScreenHeading;
// SCREEN: ui_gridScreen
void ui_gridScreen_screen_init(void);
void ui_event_gridScreen(lv_event_t * e);
extern lv_obj_t * ui_gridScreen;
extern lv_obj_t * ui_gridScreenHeading;
// SCREEN: ui_battScreen
void ui_battScreen_screen_init(void);
void ui_event_battScreen(lv_event_t * e);
extern lv_obj_t * ui_battScreen;
extern lv_obj_t * ui_battScreenHeading;
extern lv_obj_t * ui_battIcon2;
extern lv_obj_t * ui_battCapLabel;
extern lv_obj_t * ui_battCapValue;
extern lv_obj_t * ui_battSocLabel;
extern lv_obj_t * ui_battSocValue;
extern lv_obj_t * ui_battPwrLabel;
extern lv_obj_t * ui_battPwrValue;
extern lv_obj_t * ui_battCurrLabel;
extern lv_obj_t * ui_battCurrValue;
extern lv_obj_t * ui_voltLabel;
extern lv_obj_t * ui_battVoltValue;
extern lv_obj_t * ui_tempLabel;
extern lv_obj_t * ui_battTempValue;
// SCREEN: ui_loadScreen
void ui_loadScreen_screen_init(void);
void ui_event_loadScreen(lv_event_t * e);
extern lv_obj_t * ui_loadScreen;
extern lv_obj_t * ui_loadScreenHeading;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_1549501229);    // assets\icons8-solar-panel-100.png
LV_IMG_DECLARE(ui_img_1933564998);    // assets\line-75-4.png
LV_IMG_DECLARE(ui_img_670870020);    // assets\icons8-charging-battery-90.png
LV_IMG_DECLARE(ui_img_1261930360);    // assets\line-75-4-inv.png
LV_IMG_DECLARE(ui_img_705529016);    // assets\icons8-arrow-30.png
LV_IMG_DECLARE(ui_img_264836261);    // assets\icons8-transmission-tower-100.png
LV_IMG_DECLARE(ui_img_1076282785);    // assets\icons8-house-100.png
LV_IMG_DECLARE(ui_img_1551709364);    // assets\sunsynk-logo-40px.png
LV_IMG_DECLARE(ui_img_1765460539);    // assets\icons8-transfer-24 (1).png
LV_IMG_DECLARE(ui_img_1683162281);    // assets\icons8-wifi-26.png
LV_IMG_DECLARE(ui_img_1288183160);    // assets\icons8-wifi-26-med.png
LV_IMG_DECLARE(ui_img_811431924);    // assets\icons8-wifi-26-low.png
LV_IMG_DECLARE(ui_img_226794803);    // assets\icons8-settings-24-1.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
