// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Solar_UI_480x320

#include "../ui.h"

void ui_loadScreen_screen_init(void)
{
    ui_loadScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_loadScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_loadScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_loadScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_loadScreenHeading = lv_label_create(ui_loadScreen);
    lv_obj_set_width(ui_loadScreenHeading, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_loadScreenHeading, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_loadScreenHeading, 0);
    lv_obj_set_y(ui_loadScreenHeading, -140);
    lv_obj_set_align(ui_loadScreenHeading, LV_ALIGN_CENTER);
    lv_label_set_text(ui_loadScreenHeading, "LOAD");
    lv_obj_set_style_text_color(ui_loadScreenHeading, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_loadScreenHeading, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_loadScreenHeading, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_loadScreen, ui_event_loadScreen, LV_EVENT_ALL, NULL);

}
