// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Solar_UI_480x320

#include "../ui.h"

void ui_plot_screen_init(void)
{
    ui_plot = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_plot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_plot, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_plot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dailyFlow = lv_chart_create(ui_plot);
    lv_obj_set_width(ui_dailyFlow, 380);
    lv_obj_set_height(ui_dailyFlow, 240);
    lv_obj_set_align(ui_dailyFlow, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_dailyFlow, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_dailyFlow, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_dailyFlow, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_dailyFlow, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_obj_set_style_bg_color(ui_dailyFlow, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dailyFlow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_plot, ui_event_plot, LV_EVENT_ALL, NULL);

}
