// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Solar_UI_480x320

#include "../ui.h"

void ui_pvScreen_screen_init(void)
{
    ui_pvScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_pvScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pvScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pvScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pvScreenHeading = lv_label_create(ui_pvScreen);
    lv_obj_set_width(ui_pvScreenHeading, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pvScreenHeading, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pvScreenHeading, 0);
    lv_obj_set_y(ui_pvScreenHeading, -140);
    lv_obj_set_align(ui_pvScreenHeading, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pvScreenHeading, "SOLAR");
    lv_obj_set_style_text_color(ui_pvScreenHeading, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pvScreenHeading, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_pvScreenHeading, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pvScreenHeading, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_pvScreen, ui_event_pvScreen, LV_EVENT_ALL, NULL);

}
